# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-19 05:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Registrationapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='key',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
    ]
